# Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
# This product includes software developed at Datadog (https://www.datadoghq.com/) Copyright 2025 Datadog, Inc.

# DO NOT EDIT: This file is generated by terraform-autogen. Update the autogen_config.json file to change the generated code.

output "container_app_environment_id" {
  description = <<DESCRIPTION
The ID of the Container App Environment to host this Container App.
DESCRIPTION
  value       = azurerm_container_app.this.container_app_environment_id
}

output "custom_domain_verification_id" {
  description = <<DESCRIPTION
The ID of the Custom Domain Verification for this Container App.
DESCRIPTION
  value       = azurerm_container_app.this.custom_domain_verification_id
  sensitive   = true
}

output "id" {
  value = azurerm_container_app.this.id
}

output "latest_revision_fqdn" {
  description = <<DESCRIPTION
The FQDN of the Latest Revision of the Container App.
DESCRIPTION
  value       = azurerm_container_app.this.latest_revision_fqdn
}

output "latest_revision_name" {
  description = <<DESCRIPTION
The name of the latest Container Revision.
DESCRIPTION
  value       = azurerm_container_app.this.latest_revision_name
}

output "location" {
  value = azurerm_container_app.this.location
}

output "max_inactive_revisions" {
  value = azurerm_container_app.this.max_inactive_revisions
}

output "name" {
  description = <<DESCRIPTION
The name for this Container App.
DESCRIPTION
  value       = azurerm_container_app.this.name
}

output "outbound_ip_addresses" {
  value = azurerm_container_app.this.outbound_ip_addresses
}

output "resource_group_name" {
  value = azurerm_container_app.this.resource_group_name
}

output "revision_mode" {
  value = azurerm_container_app.this.revision_mode
}

output "tags" {
  value = azurerm_container_app.this.tags
}

output "workload_profile_name" {
  value = azurerm_container_app.this.workload_profile_name
}

output "dapr" {
  value = azurerm_container_app.this.dapr
}

output "identity" {
  value = azurerm_container_app.this.identity
}

output "ingress" {
  value = azurerm_container_app.this.ingress
}

output "registry" {
  value = azurerm_container_app.this.registry
}

output "secret" {
  value     = azurerm_container_app.this.secret
  sensitive = true
}

output "template" {
  value = azurerm_container_app.this.template
}

output "timeouts" {
  value = azurerm_container_app.this.timeouts
}
