# Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
# This product includes software developed at Datadog (https://www.datadoghq.com/) Copyright 2025 Datadog, Inc.

# DO NOT EDIT: This file is generated by terraform-autogen. Update the autogen_config.json file to change the generated code.

output "container_app_environment_id" {
  description = <<DESCRIPTION
The ID of the Container App Environment to host this Container App.
DESCRIPTION
  value       = azurerm_container_app.this.container_app_environment_id
}

output "custom_domain_verification_id" {
  description = <<DESCRIPTION
The ID of the Custom Domain Verification for this Container App.
DESCRIPTION
  value       = azurerm_container_app.this.custom_domain_verification_id
  sensitive   = true
}

output "id" {
  description = <<DESCRIPTION
The ID of the Container App.
DESCRIPTION
  value       = azurerm_container_app.this.id
}

output "latest_revision_fqdn" {
  description = <<DESCRIPTION
The FQDN of the Latest Revision of the Container App.
DESCRIPTION
  value       = azurerm_container_app.this.latest_revision_fqdn
}

output "latest_revision_name" {
  description = <<DESCRIPTION
The name of the latest Container Revision.
DESCRIPTION
  value       = azurerm_container_app.this.latest_revision_name
}

output "location" {
  description = <<DESCRIPTION
The location this Container App is deployed in. This is the same as the Environment in which it is deployed.
DESCRIPTION
  value       = azurerm_container_app.this.location
}

output "max_inactive_revisions" {
  description = <<DESCRIPTION
The maximum of inactive revisions allowed for this Container App.
DESCRIPTION
  value       = azurerm_container_app.this.max_inactive_revisions
}

output "name" {
  description = <<DESCRIPTION
The name for this Container App.
DESCRIPTION
  value       = azurerm_container_app.this.name
}

output "outbound_ip_addresses" {
  description = <<DESCRIPTION
A list of the Public IP Addresses which the Container App uses for outbound network access.
DESCRIPTION
  value       = azurerm_container_app.this.outbound_ip_addresses
}

output "resource_group_name" {
  description = <<DESCRIPTION
The name of the resource group in which the Container App Environment is to be created. Changing this forces a new resource to be created.
DESCRIPTION
  value       = azurerm_container_app.this.resource_group_name
}

output "revision_mode" {
  description = <<DESCRIPTION
The revisions operational mode for the Container App. Possible values include `Single` and `Multiple`. In `Single` mode, a single revision is in operation at any given time. In `Multiple` mode, more than one revision can be active at a time and can be configured with load distribution via the `traffic_weight` block in the `ingress` configuration.
DESCRIPTION
  value       = azurerm_container_app.this.revision_mode
}

output "tags" {
  description = <<DESCRIPTION
A mapping of tags to assign to the Container App.
DESCRIPTION
  value       = azurerm_container_app.this.tags
}

output "workload_profile_name" {
  description = <<DESCRIPTION
The name of the Workload Profile in the Container App Environment to place this Container App.
DESCRIPTION
  value       = azurerm_container_app.this.workload_profile_name
}

output "dapr" {
  description = <<DESCRIPTION
A `dapr` block as detailed below.
DESCRIPTION
  value       = azurerm_container_app.this.dapr
}

output "identity" {
  description = <<DESCRIPTION
An `identity` block as detailed below.
DESCRIPTION
  value       = azurerm_container_app.this.identity
}

output "ingress" {
  description = <<DESCRIPTION
An `ingress` block as detailed below.
DESCRIPTION
  value       = azurerm_container_app.this.ingress
}

output "registry" {
  description = <<DESCRIPTION
A `registry` block as detailed below.
DESCRIPTION
  value       = azurerm_container_app.this.registry
}

output "secret" {
  description = <<DESCRIPTION
One or more `secret` block as detailed below.
DESCRIPTION
  value       = azurerm_container_app.this.secret
  sensitive   = true
}

output "template" {
  description = <<DESCRIPTION
A `template` block as detailed below.
DESCRIPTION
  value       = azurerm_container_app.this.template
}

output "timeouts" {
  value = azurerm_container_app.this.timeouts
}
